In [ ]:
#NumPy:- is stands for Numerical Python. It's the foundational package for mathematical computing. Mathemetical and logical
#        opetation on arrays. Operation related to linear algebra. Numpy has in-built functions for linear algebra and
#        random number generation. ndarray is core object in NumPy.

#     Basic ndarray:- 
            # Multidimensinal Array
            # Homogeneous collection of values.
            # Fast and efficient
            # Support for mathematical functions
            # Primary container for data exchange between python algorithms.
            
#     Syntax:- class numpy.matrix(data, dtype=None, copy = True)
#       # data -> array_like or String
        #    If 'data' is string, it is interpreted as a matrix with commas or spaces spearating columns, and semicolons
        #    separating rows.
        
        # dtype -> data-type
        #    Data type of the output matrix.
        
        # bool
        #    If data is already an ndarray, then this flag determines whether the data is copied(default),
        #    or view is constructed.
        
#     Attribute:
        # T  Returns the transpose of the matrix.

In [21]:
#Linear Algebra:- 

import numpy as np
import time

array = np.matrix('1,2; 3,4')           # matrix function return matrix from an array-like object, of from a string of data.
print(array)                            # A matrix is a specialized 2-D array that retains its 2-D nature through operation.

[[1 2]
 [3 4]]


In [22]:
# for type of 'array' object 
print(type(array))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [23]:
# for getting dimensions
print(array.ndim)

2


In [24]:
# for shape of array
print(array.shape)

(2, 2)


In [25]:
# for size
print(array.size)

4


In [26]:
# for type of elements in array
print(array.dtype)

int32


In [27]:
y = np.matrix([[3,1,4], [1,5,9], [2,6,5]])
print(y)

[[3 1 4]
 [1 5 9]
 [2 6 5]]


In [28]:
y.T                                 # Returns the transpose of the matix

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [29]:
y.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [30]:
z = np.matrix([[0, 0, 1], [2, -1, 3], [1, 1, 4]])
print(z)

[[ 0  0  1]
 [ 2 -1  3]
 [ 1  1  4]]


In [31]:
z.T

matrix([[ 0,  2,  1],
        [ 0, -1,  1],
        [ 1,  3,  4]])

In [32]:
z.I

matrix([[-2.33333333,  0.33333333,  0.33333333],
        [-1.66666667, -0.33333333,  0.66666667],
        [ 1.        ,  0.        ,  0.        ]])

In [34]:
import numpy as np
import time

a = [1,2,3,4]
b = [10, 11, 12, 13]

print(a+b)

output = []
for a, b in zip(a,b):
    output.append(a + b)

print(output)

[1, 2, 3, 4, 10, 11, 12, 13]
[11, 13, 15, 17]


In [35]:
g = list(range(1000))
%timeit sum(g)

9.33 µs ± 984 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
x = np.array(g)
%timeit np.sum(x)

3.54 µs ± 47.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
